version: "3.8"

services:

  app:
    build: .
    container_name: Girllette
    ports:
      - "4000:4000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: girllette

  db:
    image: mysql:8
    container_name: girllette-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: girllette
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

volumes:
  mysql-data: